services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ${STACKIT_KEY_FILE:-../../.keys/scraper.json}:/app/keys/scraper.json:ro

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
