# Jib container image configuration
quarkus.container-image.builder=jib
quarkus.container-image.build=false
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=harald-landvoigt/stackit-resource-explorer
quarkus.container-image.name=backend
quarkus.container-image.tag=${CONTAINER_IMAGE_TAG:${quarkus.application.version}}
quarkus.container-image.additional-tags=latest
quarkus.container-image.labels."org.opencontainers.image.source"=https://github.com/harald-landvoigt/stackit-resource-explorer
quarkus.container-image.labels."org.opencontainers.image.description"="STACKIT Resource Explorer Backend API"
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24
quarkus.jib.user=185

# Datasource & Database Configuration
quarkus.datasource.db-kind=postgresql

# Flyway Database Migration Configuration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# Hibernate ORM Configuration
quarkus.hibernate-orm.schema-management.strategy=validate
# Required by Quarkus when using @JdbcTypeCode(SqlTypes.JSON) with default Jackson mapper
quarkus.hibernate-orm.mapping.format.global=ignore

# StackIT SDK Configuration
stackit.sdk.service-account-key-path=${STACKIT_SERVICE_ACCOUNT_KEY_PATH:/app/keys/scraper.json}
%dev.stackit.sdk.service-account-key-path=${STACKIT_SERVICE_ACCOUNT_KEY_PATH:../../.keys/scraper.json}
%test.stackit.sdk.service-account-key-path=${STACKIT_SERVICE_ACCOUNT_KEY_PATH:../../.keys/scraper.json}

# Scrapers Schedule Configuration
stackit.compute.schedule=1h
stackit.storage.schedule=1h
stackit.network.schedule=1h
stackit.network-vpc.schedule=1h
stackit.vmdisks.schedule=1h
stackit.iam.schedule=1h
stackit.billing.schedule=1h

# Test Configuration
%test.quarkus.http.test-port=0
%test.quarkus.scheduler.enabled=false
